// Robo Anim BP
//
// UE4 name of this class: Robo_AnimBP_C

// UE4 Asset Name: Robo_AnimBP
// UE4 Package Name: "/Game/Character/Robo/Robo_AnimBP"

annotations: &reflected_data &name("Robo_AnimBP_C")

$$ @

&raw("IsInAir?") Boolean !@is_in_air? // Is in Air?
&raw("Speed")    Real    !@speed      // Speed

$$ @anim_graph
// Anim Graph
//
// UE4 name of this method: AnimGraph

&aka("AnimGraph")

(PoseLink anim_graph : PoseLink!) 

$$ .
