// Third Person Anim BP
//
// UE4 name of this class: ThirdPerson_AnimBP_C

// UE4 Asset Name: ThirdPerson_AnimBP
// UE4 Package Name: "/Game/Character/Mannequin/Animations/ThirdPerson_AnimBP"

annotations: &reflected_data &name("ThirdPerson_AnimBP_C")

$$ @

&raw("IsInAir?") Boolean !@is_in_air? // Is in Air?
&raw("Speed")    Real    !@speed      // Speed

$$ @anim_graph
// Anim Graph
//
// UE4 name of this method: AnimGraph

&aka("AnimGraph")

(PoseLink anim_graph : PoseLink!) 

$$ .
