// BP Projectile Spline
//
// UE4 name of this class: BP_ProjectileSpline_C

// UE4 Asset Name: BP_ProjectileSpline
// UE4 Package Name: "/Game/Blueprints/Projectiles/BP_ProjectileSpline"

annotations: &reflected_data &name("BP_ProjectileSpline_C")

$$ @

/* &raw("SkookumScriptClassData")SkookumScriptClassDataComponent !@skookum_script_class_data // Currently unsupported */
&raw("Spline") SplineComponent !@spline // Spline

$$ .
