// Pivot Painter 16bit Texture Alpha Data Types
//
// UE4 name of this enum: PivotPainter16bitTextureAlphaDataTypes

// UE4 Asset Name: PivotPainter16bitTextureAlphaDataTypes
// UE4 Package Name: "/Niagara/Functions/PivotPainter/PivotPainter16bitTextureAlphaDataTypes"

annotations: &reflected_data &name("PivotPainter16bitTextureAlphaDataTypes")

$$ @@

PivotPainter16bitTextureAlphaDataTypes !@@number_of_steps_to_root
PivotPainter16bitTextureAlphaDataTypes !@@random_0_1
PivotPainter16bitTextureAlphaDataTypes !@@origin_extents_16_bit_
PivotPainter16bitTextureAlphaDataTypes !@@bounding_box_diameter
PivotPainter16bitTextureAlphaDataTypes !@@selection_order_int_as_float_
PivotPainter16bitTextureAlphaDataTypes !@@normalized_0_1_hierarchy_position
PivotPainter16bitTextureAlphaDataTypes !@@object_x_width
PivotPainter16bitTextureAlphaDataTypes !@@object_y_depth
PivotPainter16bitTextureAlphaDataTypes !@@object_z_height
PivotPainter16bitTextureAlphaDataTypes !@@parent_index_float_up_to_2048_
PivotPainter16bitTextureAlphaDataTypes !@@pivot_painter_16bit_texture_alpha_data_types_max

$$ @@!
// PivotPainter16bitTextureAlphaDataTypes
// EnumPath: /Niagara/Functions/PivotPainter/PivotPainter16bitTextureAlphaDataTypes.PivotPainter16bitTextureAlphaDataTypes

()

  [
  @@number_of_steps_to_root:                          PivotPainter16bitTextureAlphaDataTypes!int(0)
  @@random_0_1:                                       PivotPainter16bitTextureAlphaDataTypes!int(1)
  @@origin_extents_16_bit_:                           PivotPainter16bitTextureAlphaDataTypes!int(2)
  @@bounding_box_diameter:                            PivotPainter16bitTextureAlphaDataTypes!int(3)
  @@selection_order_int_as_float_:                    PivotPainter16bitTextureAlphaDataTypes!int(4)
  @@normalized_0_1_hierarchy_position:                PivotPainter16bitTextureAlphaDataTypes!int(5)
  @@object_x_width:                                   PivotPainter16bitTextureAlphaDataTypes!int(6)
  @@object_y_depth:                                   PivotPainter16bitTextureAlphaDataTypes!int(7)
  @@object_z_height:                                  PivotPainter16bitTextureAlphaDataTypes!int(8)
  @@parent_index_float_up_to_2048_:                   PivotPainter16bitTextureAlphaDataTypes!int(9)
  @@pivot_painter_16bit_texture_alpha_data_types_max: PivotPainter16bitTextureAlphaDataTypes!int(10)
  ]

$$ .
