// A SceneComponent has a transform and supports attachment, but has no rendering or collision capabilities.
// Useful as a 'dummy' component in the hierarchy to offset others.
// @see [Scene Components](https://docs.unrealengine.com/latest/INT/Programming/UnrealArchitecture/Actors/Components/index.html#scenecomponents)
//
// UE4 name of this class: SceneComponent

annotations: &reflected_cpp &name("SceneComponent")

$$ .
