// SK Bot Skeleton Anim Blueprint
//
// UE4 name of this class: SK_bot_Skeleton_AnimBlueprint_C

// UE4 Asset Name: SK_bot_Skeleton_AnimBlueprint
// UE4 Package Name: "/Game/Models/Bot_1/SK_bot_Skeleton_AnimBlueprint"

annotations: &reflected_data &name("SK_bot_Skeleton_AnimBlueprint_C")

$$ @

&raw("BotAnim") E_BotAnimState !@bot_anim // Bot Anim

$$ @anim_graph
// Anim Graph
//
// UE4 name of this method: AnimGraph

&aka("AnimGraph")

(PoseLink anim_graph : PoseLink!) 

$$ .
